version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
os: Visual Studio 2015
init:
- cmd: rd /s /q %CHOCOLATEYINSTALL%
- ps: iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))
install:
- cinst cmake -y
- remove_python27_from_path.bat
- set "PATH=%PATH%;C:\Python34"
- python --version
- python -m pip install -U setuptools pip
- python -m pip install EmPy
- python -m pip install trollius
- git submodule update --init --recursive
- '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64'
- set "PATH=%PATH%;C:\Python34"
build_script:
- python -u ament\ament_tools\scripts\ament.py build . --ament-cmake-args -- -j1
deploy: off
